### ISSUE TITLE
HTTP Error 429 while sending objects to Object Storage

### ISSUE THREAD

**Issue by annelhote** [dataesr/harvest-pubmed#5]
Stacktrace :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/v3/client.py", line 343, in get_raw_token_from_identity_service
    return plugin.get_auth_ref(self.session)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/auth/identity/v3/base.py", line 189, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/session.py", line 543, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/session.py", line 443, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.HTTPClientError: HTTP Client Error (HTTP 429)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 636, in get_auth_keystone
    auth_url=auth_url, insecure=insecure, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/v3/client.py", line 267, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/httpclient.py", line 583, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/v3/client.py", line 353, in get_raw_token_from_identity_service
    _('Authorization failed: %s') % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization failed: HTTP Client Error (HTTP 429)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 1031, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 749, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 772, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/src/pubmed/server/main/tasks.py", line 17, in create_task_pubmed
    pubmed_to_json(date=date)
  File "/src/pubmed/server/main/pubmed_parse.py", line 287, in pubmed_to_json
    df_publis = parse_pubmed_one_date(date=date)
  File "/src/pubmed/server/main/pubmed_parse.py", line 271, in parse_pubmed_one_date
    set_objects(conn=conn, date=date, all_objects=df_publis, container='pubmed', path='parsed')
  File "/src/pubmed/server/main/utils_swift.py", line 71, in set_objects
    conn.put_object(container, get_notice_filename(date, path), contents=gz_buffer.getvalue())
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 1908, in put_object
    response_dict=response_dict)
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 1736, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 1688, in get_auth
    timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 734, in get_auth
    auth_version=auth_version)
  File "/usr/local/lib/python3.6/site-packages/swiftclient/client.py", line 644, in get_auth_keystone
    raise ClientException('Authorization Failure. %s' % err)
swiftclient.exceptions.ClientException: Authorization Failure. Authorization failed: HTTP Client Error (HTTP 429)
```

**Comment by annelhote** [comment]
[WRONG] See https://community.ovh.com/t/object-storage-too-many-requests/2687/4

**Comment by annelhote** [comment]
[WRONG] We might reach a limit about sending big files with OpenStack. Let's use the same workaround : https://github.com/dataesr/bso-publications/blob/98eb9abf252f89d09c0ba81ab814c87c573d50fb/bso/server/main/utils_swift.py#L41-L47

**Comment by annelhote** [comment]
It was more an error encounter while parsing the pubmed notice, so the script was trying to redownload each day of pubmed, raising the error of too many requests.
